/**
 * The curated SAT vocabulary bank.
 *
 * This list is the *fixed* half of vocabulary practice: the words themselves,
 * their definitions, and the metadata used to build multiple-choice items.
 * The *variable* half — the sentence a word is drilled in — is written by
 * Gemini at generation time (see `lib/vocab/prompts.ts`), so a student never
 * memorizes "the sentence for obdurate"; they meet the word in fresh context
 * every few sessions.
 *
 * ── Why a hand-curated list rather than asking a model for words ──
 * A finite list is the only way to answer "how much of the SAT vocabulary has
 * he actually learned?" Mastery is tracked per word in `vocab_mastery`, so the
 * denominator has to be stable. A model asked for "SAT words" drifts between
 * calls, repeats common ones, and silently never surfaces others.
 *
 * ── Fields ──
 * - `word`       the headword, lowercase.
 * - `pos`        part of speech. Distractors are always drawn from the same
 *                part of speech, otherwise the sentence's grammar gives the
 *                answer away without any knowledge of meaning.
 * - `definition` a short student-facing gloss, shown in feedback.
 * - `tier`       1 = most frequently tested / most foundational, 3 = hardest.
 *                Students progress tier by tier (see `lib/vocab/select.ts`).
 * - `sense`      a coarse semantic cluster. Distractors are never drawn from
 *                the same `sense` as the target — that's what stops
 *                "obdurate" from being offered against "intransigent", where
 *                both genuinely fit the blank and the item has no right
 *                answer. Words with no close cousins in the list can omit it.
 *
 * Adding words: keep definitions to one clause, and give a `sense` tag to any
 * word that shares a meaning with something already here. An untagged
 * near-synonym pair is the one way to produce an unanswerable item.
 */

export type PartOfSpeech = "adj" | "noun" | "verb" | "adv";

export interface VocabWord {
  word: string;
  pos: PartOfSpeech;
  definition: string;
  tier: 1 | 2 | 3;
  sense?: string;
}

export const VOCAB_WORDS: VocabWord[] = [
  // ─── Tier 1 — high-frequency, foundational ────────────────────────
  { word: "abstract", pos: "adj", definition: "existing as an idea rather than a physical thing", tier: 1, sense: "theoretical" },
  { word: "adverse", pos: "adj", definition: "harmful or unfavorable", tier: 1, sense: "harmful" },
  { word: "advocate", pos: "verb", definition: "to publicly support or argue for", tier: 1, sense: "support" },
  { word: "aesthetic", pos: "adj", definition: "concerned with beauty or artistic appearance", tier: 1 },
  { word: "alleviate", pos: "verb", definition: "to make a problem or pain less severe", tier: 1, sense: "lessen" },
  { word: "ambiguous", pos: "adj", definition: "open to more than one interpretation", tier: 1, sense: "unclear" },
  { word: "ambivalent", pos: "adj", definition: "having mixed or conflicting feelings", tier: 1, sense: "undecided" },
  { word: "analogous", pos: "adj", definition: "similar in a way that allows comparison", tier: 1, sense: "similar" },
  { word: "anecdote", pos: "noun", definition: "a short personal story used as evidence", tier: 1 },
  { word: "anomaly", pos: "noun", definition: "something that deviates from what is normal", tier: 1, sense: "oddity" },
  { word: "arbitrary", pos: "adj", definition: "based on personal whim rather than reason", tier: 1, sense: "random" },
  { word: "articulate", pos: "adj", definition: "able to express ideas clearly and fluently", tier: 1, sense: "clear-speech" },
  { word: "assert", pos: "verb", definition: "to state something firmly and confidently", tier: 1, sense: "claim" },
  { word: "attribute", pos: "verb", definition: "to credit something as the cause or source", tier: 1 },
  { word: "augment", pos: "verb", definition: "to make something greater by adding to it", tier: 1, sense: "increase" },
  { word: "benevolent", pos: "adj", definition: "kind and generous toward others", tier: 1, sense: "kind" },
  { word: "bolster", pos: "verb", definition: "to strengthen or support", tier: 1, sense: "strengthen" },
  { word: "candid", pos: "adj", definition: "honest and direct, even when uncomfortable", tier: 1, sense: "frank" },
  { word: "coherent", pos: "adj", definition: "logically consistent and easy to follow", tier: 1, sense: "orderly" },
  { word: "compelling", pos: "adj", definition: "convincing enough to demand attention", tier: 1, sense: "persuasive" },
  { word: "complacent", pos: "adj", definition: "smugly satisfied and unaware of danger", tier: 1, sense: "self-satisfied" },
  { word: "comprehensive", pos: "adj", definition: "complete, covering everything relevant", tier: 1, sense: "thorough" },
  { word: "concede", pos: "verb", definition: "to admit that something is true after resisting", tier: 1, sense: "yield" },
  { word: "conciliatory", pos: "adj", definition: "intended to soothe anger and restore goodwill", tier: 1, sense: "peacemaking" },
  { word: "condone", pos: "verb", definition: "to accept or overlook behavior that is wrong", tier: 1, sense: "tolerate" },
  { word: "conspicuous", pos: "adj", definition: "clearly visible and attracting notice", tier: 1, sense: "noticeable" },
  { word: "contemporary", pos: "adj", definition: "belonging to the same time period, or modern", tier: 1 },
  { word: "convey", pos: "verb", definition: "to communicate an idea or feeling", tier: 1, sense: "express" },
  { word: "credible", pos: "adj", definition: "believable and worthy of trust", tier: 1, sense: "trustworthy" },
  { word: "cultivate", pos: "verb", definition: "to develop something deliberately over time", tier: 1, sense: "nurture" },
  { word: "curtail", pos: "verb", definition: "to cut short or reduce", tier: 1, sense: "lessen" },
  { word: "deficient", pos: "adj", definition: "lacking something necessary", tier: 1, sense: "insufficient" },
  { word: "deliberate", pos: "adj", definition: "done intentionally and with care", tier: 1, sense: "intentional" },
  { word: "denounce", pos: "verb", definition: "to condemn publicly", tier: 1, sense: "criticize" },
  { word: "depict", pos: "verb", definition: "to represent or portray", tier: 1, sense: "express" },
  { word: "deter", pos: "verb", definition: "to discourage someone from acting", tier: 1, sense: "discourage" },
  { word: "detrimental", pos: "adj", definition: "causing harm or damage", tier: 1, sense: "harmful" },
  { word: "diligent", pos: "adj", definition: "showing careful and persistent effort", tier: 1, sense: "hardworking" },
  { word: "diminish", pos: "verb", definition: "to become or make smaller", tier: 1, sense: "lessen" },
  { word: "discern", pos: "verb", definition: "to perceive or recognize something subtle", tier: 1, sense: "perceive" },
  { word: "disparage", pos: "verb", definition: "to speak of someone as unimportant", tier: 1, sense: "belittle" },
  { word: "diverse", pos: "adj", definition: "showing a great deal of variety", tier: 1, sense: "varied" },
  { word: "elaborate", pos: "verb", definition: "to explain in greater detail", tier: 1 },
  { word: "elusive", pos: "adj", definition: "difficult to find, catch, or define", tier: 1, sense: "hard-to-grasp" },
  { word: "empirical", pos: "adj", definition: "based on observation or experiment rather than theory", tier: 1, sense: "evidence-based" },
  { word: "endorse", pos: "verb", definition: "to declare public approval of", tier: 1, sense: "support" },
  { word: "enhance", pos: "verb", definition: "to improve the quality or value of", tier: 1, sense: "improve" },
  { word: "exemplify", pos: "verb", definition: "to serve as a typical example of", tier: 1 },
  { word: "explicit", pos: "adj", definition: "stated clearly and leaving no room for doubt", tier: 1, sense: "direct" },
  { word: "feasible", pos: "adj", definition: "possible to do easily or practically", tier: 1, sense: "workable" },
  { word: "fluctuate", pos: "verb", definition: "to rise and fall irregularly", tier: 1, sense: "vary" },
  { word: "fundamental", pos: "adj", definition: "forming the necessary base of something", tier: 1, sense: "basic" },
  { word: "hinder", pos: "verb", definition: "to make progress difficult", tier: 1, sense: "obstruct" },
  { word: "hypothesis", pos: "noun", definition: "a proposed explanation to be tested", tier: 1 },
  { word: "illustrate", pos: "verb", definition: "to make clear by giving an example", tier: 1 },
  { word: "implicit", pos: "adj", definition: "suggested without being directly stated", tier: 1, sense: "indirect" },
  { word: "inadvertent", pos: "adj", definition: "not intended or deliberate", tier: 1, sense: "accidental" },
  { word: "incentive", pos: "noun", definition: "something that motivates action", tier: 1 },
  { word: "indifferent", pos: "adj", definition: "having no interest or concern", tier: 1, sense: "uncaring" },
  { word: "inevitable", pos: "adj", definition: "certain to happen and impossible to avoid", tier: 1, sense: "unavoidable" },
  { word: "infer", pos: "verb", definition: "to conclude from evidence rather than direct statement", tier: 1, sense: "perceive" },
  { word: "innovative", pos: "adj", definition: "featuring new methods or ideas", tier: 1, sense: "original" },
  { word: "integral", pos: "adj", definition: "necessary to make a whole complete", tier: 1, sense: "essential" },
  { word: "intricate", pos: "adj", definition: "having many small, interconnected parts", tier: 1, sense: "complex" },
  { word: "intrinsic", pos: "adj", definition: "belonging naturally to something's essential nature", tier: 1, sense: "inherent" },
  { word: "justify", pos: "verb", definition: "to show that something is reasonable or right", tier: 1, sense: "defend" },
  { word: "lucid", pos: "adj", definition: "expressed clearly and easy to understand", tier: 1, sense: "orderly" },
  { word: "meticulous", pos: "adj", definition: "showing extreme attention to detail", tier: 1, sense: "careful" },
  { word: "mitigate", pos: "verb", definition: "to make something bad less severe", tier: 1, sense: "lessen" },
  { word: "negligible", pos: "adj", definition: "so small as to be not worth considering", tier: 1, sense: "trivial" },
  { word: "novel", pos: "adj", definition: "new and unlike anything before", tier: 1, sense: "original" },
  { word: "nuanced", pos: "adj", definition: "characterized by subtle distinctions", tier: 1, sense: "subtle" },
  { word: "objective", pos: "adj", definition: "not influenced by personal feelings", tier: 1, sense: "impartial" },
  { word: "obsolete", pos: "adj", definition: "no longer in use because something better exists", tier: 1, sense: "outdated" },
  { word: "paradox", pos: "noun", definition: "a statement that contradicts itself yet may be true", tier: 1 },
  { word: "pervasive", pos: "adj", definition: "spreading widely throughout something", tier: 1, sense: "widespread" },
  { word: "plausible", pos: "adj", definition: "seeming reasonable or probably true", tier: 1, sense: "believable" },
  { word: "pragmatic", pos: "adj", definition: "dealing with things practically rather than ideally", tier: 1, sense: "practical" },
  { word: "precedent", pos: "noun", definition: "an earlier case used as a guide for later ones", tier: 1 },
  { word: "profound", pos: "adj", definition: "very great, deep, or intense", tier: 1, sense: "deep" },
  { word: "prohibit", pos: "verb", definition: "to formally forbid", tier: 1, sense: "forbid" },
  { word: "prolific", pos: "adj", definition: "producing a great deal of work or fruit", tier: 1, sense: "productive" },
  { word: "prominent", pos: "adj", definition: "important and widely recognized", tier: 1, sense: "noticeable" },
  { word: "prospect", pos: "noun", definition: "the possibility of a future event", tier: 1 },
  { word: "refute", pos: "verb", definition: "to prove a claim to be wrong", tier: 1, sense: "disprove" },
  { word: "reinforce", pos: "verb", definition: "to make stronger by adding support", tier: 1, sense: "strengthen" },
  { word: "reluctant", pos: "adj", definition: "unwilling and hesitant", tier: 1, sense: "unwilling" },
  { word: "resilient", pos: "adj", definition: "able to recover quickly from difficulty", tier: 1, sense: "tough" },
  { word: "rhetoric", pos: "noun", definition: "the art of persuasive speaking or writing", tier: 1 },
  { word: "rigorous", pos: "adj", definition: "extremely thorough and demanding", tier: 1, sense: "thorough" },
  { word: "scrutiny", pos: "noun", definition: "close and critical examination", tier: 1 },
  { word: "skeptical", pos: "adj", definition: "not easily convinced; having doubts", tier: 1, sense: "doubting" },
  { word: "subtle", pos: "adj", definition: "so delicate as to be difficult to notice", tier: 1, sense: "subtle" },
  { word: "sufficient", pos: "adj", definition: "enough for a particular purpose", tier: 1, sense: "adequate" },
  { word: "superficial", pos: "adj", definition: "concerned only with the surface, not depth", tier: 1, sense: "shallow" },
  { word: "sustain", pos: "verb", definition: "to keep something going over time", tier: 1, sense: "maintain" },
  { word: "tentative", pos: "adj", definition: "not certain or fixed; provisional", tier: 1, sense: "uncertain" },
  { word: "undermine", pos: "verb", definition: "to weaken gradually from below", tier: 1, sense: "weaken" },
  { word: "viable", pos: "adj", definition: "capable of working successfully", tier: 1, sense: "workable" },
  { word: "vindicate", pos: "verb", definition: "to clear of blame or prove right", tier: 1, sense: "defend" },

  // ─── Tier 2 — solid mid-range SAT vocabulary ──────────────────────
  { word: "abate", pos: "verb", definition: "to become less intense or widespread", tier: 2, sense: "lessen" },
  { word: "aberration", pos: "noun", definition: "a temporary departure from what is normal", tier: 2, sense: "oddity" },
  { word: "acquiesce", pos: "verb", definition: "to accept something reluctantly without protest", tier: 2, sense: "yield" },
  { word: "acute", pos: "adj", definition: "sharp, severe, or keenly perceptive", tier: 2 },
  { word: "adept", pos: "adj", definition: "highly skilled at something", tier: 2, sense: "skilled" },
  { word: "admonish", pos: "verb", definition: "to warn or scold gently but firmly", tier: 2, sense: "criticize" },
  { word: "affable", pos: "adj", definition: "friendly and easy to talk to", tier: 2, sense: "friendly" },
  { word: "affinity", pos: "noun", definition: "a natural liking or connection", tier: 2 },
  { word: "aggregate", pos: "noun", definition: "a total formed by combining separate parts", tier: 2 },
  { word: "alacrity", pos: "noun", definition: "brisk and cheerful eagerness", tier: 2, sense: "eagerness" },
  { word: "allude", pos: "verb", definition: "to refer to something indirectly", tier: 2, sense: "indirect" },
  { word: "altruistic", pos: "adj", definition: "selflessly concerned for the welfare of others", tier: 2, sense: "kind" },
  { word: "amass", pos: "verb", definition: "to gather a large quantity over time", tier: 2, sense: "accumulate" },
  { word: "anachronism", pos: "noun", definition: "something placed in the wrong historical period", tier: 2 },
  { word: "antagonize", pos: "verb", definition: "to provoke hostility in someone", tier: 2, sense: "provoke" },
  { word: "apathy", pos: "noun", definition: "a total lack of interest or emotion", tier: 2, sense: "uncaring" },
  { word: "appease", pos: "verb", definition: "to calm someone by giving in to demands", tier: 2, sense: "peacemaking" },
  { word: "apprehensive", pos: "adj", definition: "anxious about something that may happen", tier: 2, sense: "fearful" },
  { word: "arduous", pos: "adj", definition: "requiring great and tiring effort", tier: 2, sense: "difficult" },
  { word: "ascertain", pos: "verb", definition: "to find out for certain", tier: 2, sense: "determine" },
  { word: "assiduous", pos: "adj", definition: "showing great care and persistence", tier: 2, sense: "hardworking" },
  { word: "astute", pos: "adj", definition: "shrewd, with sharp practical judgment", tier: 2, sense: "shrewd" },
  { word: "audacious", pos: "adj", definition: "boldly daring, often disregarding risk", tier: 2, sense: "bold" },
  { word: "austere", pos: "adj", definition: "severely plain, without comfort or decoration", tier: 2, sense: "plain" },
  { word: "banal", pos: "adj", definition: "boringly ordinary and unoriginal", tier: 2, sense: "unoriginal" },
  { word: "belie", pos: "verb", definition: "to give a false impression of", tier: 2, sense: "misrepresent" },
  { word: "brevity", pos: "noun", definition: "shortness of expression or duration", tier: 2, sense: "brief" },
  { word: "capricious", pos: "adj", definition: "given to sudden unpredictable changes of mood", tier: 2, sense: "fickle" },
  { word: "castigate", pos: "verb", definition: "to reprimand severely", tier: 2, sense: "criticize" },
  { word: "catalyst", pos: "noun", definition: "something that causes an event to happen faster", tier: 2 },
  { word: "circumvent", pos: "verb", definition: "to find a way around an obstacle or rule", tier: 2, sense: "evade" },
  { word: "clandestine", pos: "adj", definition: "kept secret because it is not permitted", tier: 2, sense: "secret" },
  { word: "cogent", pos: "adj", definition: "clear and logically convincing", tier: 2, sense: "persuasive" },
  { word: "commensurate", pos: "adj", definition: "matching in size or degree; proportional", tier: 2, sense: "proportional" },
  { word: "conducive", pos: "adj", definition: "making a particular outcome more likely", tier: 2 },
  { word: "consensus", pos: "noun", definition: "general agreement within a group", tier: 2, sense: "agreement" },
  { word: "conjecture", pos: "noun", definition: "an opinion formed without firm evidence", tier: 2, sense: "guess" },
  { word: "contentious", pos: "adj", definition: "likely to cause argument", tier: 2, sense: "disputed" },
  { word: "conventional", pos: "adj", definition: "following accepted custom rather than new ideas", tier: 2, sense: "traditional" },
  { word: "copious", pos: "adj", definition: "present in large quantities", tier: 2, sense: "abundant" },
  { word: "corroborate", pos: "verb", definition: "to confirm with supporting evidence", tier: 2, sense: "confirm" },
  { word: "culminate", pos: "verb", definition: "to reach a final climactic point", tier: 2 },
  { word: "cursory", pos: "adj", definition: "hasty and without attention to detail", tier: 2, sense: "hasty" },
  { word: "debunk", pos: "verb", definition: "to expose a belief as false", tier: 2, sense: "disprove" },
  { word: "decorum", pos: "noun", definition: "behavior that is polite and socially proper", tier: 2 },
  { word: "deference", pos: "noun", definition: "respectful submission to another's judgment", tier: 2, sense: "respect" },
  { word: "delineate", pos: "verb", definition: "to describe or outline precisely", tier: 2, sense: "describe" },
  { word: "derivative", pos: "adj", definition: "imitating someone else's work and lacking originality", tier: 2, sense: "unoriginal" },
  { word: "didactic", pos: "adj", definition: "intended to teach, often moralizing", tier: 2, sense: "instructive" },
  { word: "digress", pos: "verb", definition: "to wander from the main subject", tier: 2, sense: "stray" },
  { word: "discrepancy", pos: "noun", definition: "a difference between things that should match", tier: 2, sense: "mismatch" },
  { word: "disdain", pos: "noun", definition: "the feeling that something is unworthy of respect", tier: 2, sense: "contempt" },
  { word: "disseminate", pos: "verb", definition: "to spread information widely", tier: 2, sense: "spread" },
  { word: "dogmatic", pos: "adj", definition: "asserting opinions as unquestionable truth", tier: 2, sense: "inflexible" },
  { word: "dubious", pos: "adj", definition: "questionable or not to be relied on", tier: 2, sense: "doubting" },
  { word: "eclectic", pos: "adj", definition: "drawing from a wide range of sources", tier: 2, sense: "varied" },
  { word: "egregious", pos: "adj", definition: "outstandingly bad in an obvious way", tier: 2, sense: "shocking" },
  { word: "eloquent", pos: "adj", definition: "fluent and persuasive in speech", tier: 2, sense: "clear-speech" },
  { word: "emulate", pos: "verb", definition: "to imitate in order to match or surpass", tier: 2, sense: "imitate" },
  { word: "enigmatic", pos: "adj", definition: "mysterious and difficult to interpret", tier: 2, sense: "hard-to-grasp" },
  { word: "ephemeral", pos: "adj", definition: "lasting for a very short time", tier: 2, sense: "brief" },
  { word: "equivocal", pos: "adj", definition: "deliberately vague to avoid commitment", tier: 2, sense: "unclear" },
  { word: "erudite", pos: "adj", definition: "having deep scholarly knowledge", tier: 2, sense: "learned" },
  { word: "exacerbate", pos: "verb", definition: "to make a bad situation worse", tier: 2, sense: "worsen" },
  { word: "exhaustive", pos: "adj", definition: "leaving no part unexamined", tier: 2, sense: "thorough" },
  { word: "exonerate", pos: "verb", definition: "to officially clear of wrongdoing", tier: 2, sense: "defend" },
  { word: "extol", pos: "verb", definition: "to praise enthusiastically", tier: 2, sense: "praise" },
  { word: "facilitate", pos: "verb", definition: "to make a process easier", tier: 2, sense: "help" },
  { word: "fastidious", pos: "adj", definition: "excessively concerned with detail and cleanliness", tier: 2, sense: "careful" },
  { word: "frivolous", pos: "adj", definition: "not serious enough to deserve attention", tier: 2, sense: "trivial" },
  { word: "futile", pos: "adj", definition: "incapable of producing any useful result", tier: 2, sense: "pointless" },
  { word: "garrulous", pos: "adj", definition: "excessively talkative about trivial things", tier: 2, sense: "wordy" },
  { word: "gregarious", pos: "adj", definition: "fond of company and sociable", tier: 2, sense: "friendly" },
  { word: "hackneyed", pos: "adj", definition: "overused to the point of being meaningless", tier: 2, sense: "unoriginal" },
  { word: "haughty", pos: "adj", definition: "arrogantly superior toward others", tier: 2, sense: "arrogant" },
  { word: "impede", pos: "verb", definition: "to slow down or block progress", tier: 2, sense: "obstruct" },
  { word: "imperative", pos: "adj", definition: "absolutely necessary and urgent", tier: 2, sense: "essential" },
  { word: "impetuous", pos: "adj", definition: "acting quickly without thought", tier: 2, sense: "rash" },
  { word: "inclination", pos: "noun", definition: "a natural tendency toward something", tier: 2 },
  { word: "incessant", pos: "adj", definition: "continuing without pause", tier: 2, sense: "constant" },
  { word: "indignant", pos: "adj", definition: "angry at something perceived as unfair", tier: 2, sense: "angry" },
  { word: "inept", pos: "adj", definition: "having no skill; clumsy", tier: 2, sense: "unskilled" },
  { word: "innocuous", pos: "adj", definition: "harmless and unlikely to offend", tier: 2, sense: "harmless" },
  { word: "insipid", pos: "adj", definition: "lacking flavor, interest, or vigor", tier: 2, sense: "dull" },
  { word: "intransigent", pos: "adj", definition: "refusing absolutely to change one's position", tier: 2, sense: "inflexible" },
  { word: "juxtapose", pos: "verb", definition: "to place side by side for contrast", tier: 2 },
  { word: "laconic", pos: "adj", definition: "using very few words", tier: 2, sense: "brief" },
  { word: "lament", pos: "verb", definition: "to express deep sorrow or regret", tier: 2, sense: "mourn" },
  { word: "lethargic", pos: "adj", definition: "sluggish and lacking energy", tier: 2, sense: "tired" },
  { word: "meager", pos: "adj", definition: "lacking in quantity or quality", tier: 2, sense: "insufficient" },
  { word: "mundane", pos: "adj", definition: "lacking interest; of the everyday world", tier: 2, sense: "dull" },
  { word: "nostalgia", pos: "noun", definition: "sentimental longing for the past", tier: 2 },
  { word: "notorious", pos: "adj", definition: "famous for something bad", tier: 2, sense: "infamous" },
  { word: "obscure", pos: "verb", definition: "to keep from being seen or understood", tier: 2, sense: "conceal" },
  { word: "ostentatious", pos: "adj", definition: "showy in a way meant to impress", tier: 2, sense: "flashy" },
  { word: "partisan", pos: "adj", definition: "strongly biased toward one side or party", tier: 2, sense: "biased" },
  { word: "peripheral", pos: "adj", definition: "of minor importance; on the outer edge", tier: 2, sense: "marginal" },
  { word: "placate", pos: "verb", definition: "to make someone less angry", tier: 2, sense: "peacemaking" },
  { word: "precarious", pos: "adj", definition: "dangerously unstable or uncertain", tier: 2, sense: "unstable" },
  { word: "proponent", pos: "noun", definition: "a person who argues in favor of something", tier: 2, sense: "support" },
  { word: "prudent", pos: "adj", definition: "showing careful thought about the future", tier: 2, sense: "cautious" },
  { word: "reticent", pos: "adj", definition: "unwilling to share thoughts or feelings", tier: 2, sense: "reserved" },
  { word: "scathing", pos: "adj", definition: "severely and wittily critical", tier: 2, sense: "criticize" },
  { word: "spurious", pos: "adj", definition: "false despite appearing genuine", tier: 2, sense: "fake" },
  { word: "static", pos: "adj", definition: "showing no change or movement", tier: 2, sense: "unchanging" },
  { word: "substantiate", pos: "verb", definition: "to provide evidence proving something true", tier: 2, sense: "confirm" },
  { word: "superfluous", pos: "adj", definition: "more than is needed; unnecessary", tier: 2, sense: "excess" },
  { word: "tenuous", pos: "adj", definition: "very weak or slight", tier: 2, sense: "weak" },
  { word: "trivial", pos: "adj", definition: "of little value or importance", tier: 2, sense: "trivial" },
  { word: "ubiquitous", pos: "adj", definition: "present everywhere at once", tier: 2, sense: "widespread" },
  { word: "unprecedented", pos: "adj", definition: "never having happened before", tier: 2, sense: "novel-event" },
  { word: "vehement", pos: "adj", definition: "showing intense, forceful feeling", tier: 2, sense: "forceful" },
  { word: "verbose", pos: "adj", definition: "using more words than necessary", tier: 2, sense: "wordy" },
  { word: "volatile", pos: "adj", definition: "liable to change rapidly and unpredictably", tier: 2, sense: "unstable" },
  { word: "zealous", pos: "adj", definition: "showing intense enthusiasm for a cause", tier: 2, sense: "eagerness" },

  // ─── Tier 3 — hardest / lowest-frequency ──────────────────────────
  { word: "abstruse", pos: "adj", definition: "difficult to understand; obscure", tier: 3, sense: "hard-to-grasp" },
  { word: "acerbic", pos: "adj", definition: "sharp and cutting in tone", tier: 3, sense: "harsh-tone" },
  { word: "acumen", pos: "noun", definition: "keenness of judgment in a particular field", tier: 3, sense: "shrewd" },
  { word: "admonition", pos: "noun", definition: "a firm warning or gentle reprimand", tier: 3, sense: "warning" },
  { word: "aggrandize", pos: "verb", definition: "to increase power or importance, often unjustly", tier: 3, sense: "increase" },
  { word: "ameliorate", pos: "verb", definition: "to make a bad situation better", tier: 3, sense: "improve" },
  { word: "anathema", pos: "noun", definition: "something intensely disliked or cursed", tier: 3, sense: "contempt" },
  { word: "antipathy", pos: "noun", definition: "a deep-seated feeling of dislike", tier: 3, sense: "hostility" },
  { word: "apocryphal", pos: "adj", definition: "widely circulated but probably untrue", tier: 3, sense: "fake" },
  { word: "arcane", pos: "adj", definition: "known only to a few; mysteriously specialized", tier: 3, sense: "secret" },
  { word: "ascetic", pos: "adj", definition: "practicing severe self-discipline and abstinence", tier: 3, sense: "plain" },
  { word: "assuage", pos: "verb", definition: "to ease an unpleasant feeling", tier: 3, sense: "lessen" },
  { word: "avarice", pos: "noun", definition: "extreme greed for wealth", tier: 3, sense: "greed" },
  { word: "bombastic", pos: "adj", definition: "high-sounding but with little meaning", tier: 3, sense: "pompous" },
  { word: "cacophony", pos: "noun", definition: "a harsh, discordant mixture of sounds", tier: 3, sense: "noise" },
  { word: "callous", pos: "adj", definition: "insensitive to the suffering of others", tier: 3, sense: "cruel" },
  { word: "chicanery", pos: "noun", definition: "the use of trickery to achieve an aim", tier: 3, sense: "deception" },
  { word: "circumspect", pos: "adj", definition: "unwilling to take risks; wary", tier: 3, sense: "cautious" },
  { word: "complicit", pos: "adj", definition: "involved with others in wrongdoing", tier: 3 },
  { word: "conflagration", pos: "noun", definition: "a large destructive fire", tier: 3 },
  { word: "contrite", pos: "adj", definition: "feeling deep regret for wrongdoing", tier: 3, sense: "remorseful" },
  { word: "credulous", pos: "adj", definition: "too ready to believe things", tier: 3, sense: "gullible" },
  { word: "deleterious", pos: "adj", definition: "causing harm, especially gradually", tier: 3, sense: "harmful" },
  { word: "denigrate", pos: "verb", definition: "to unfairly attack someone's reputation", tier: 3, sense: "belittle" },
  { word: "desultory", pos: "adj", definition: "lacking a plan; jumping from thing to thing", tier: 3, sense: "aimless" },
  { word: "diatribe", pos: "noun", definition: "a bitter, forceful verbal attack", tier: 3, sense: "harsh-tone" },
  { word: "diffident", pos: "adj", definition: "lacking confidence in oneself", tier: 3, sense: "reserved" },
  { word: "dilatory", pos: "adj", definition: "intended to cause delay", tier: 3, sense: "slow" },
  { word: "disparate", pos: "adj", definition: "essentially different and not comparable", tier: 3, sense: "mismatch" },
  { word: "dissemble", pos: "verb", definition: "to conceal one's true motives", tier: 3, sense: "conceal" },
  { word: "ebullient", pos: "adj", definition: "overflowing with cheerful excitement", tier: 3, sense: "eagerness" },
  { word: "effusive", pos: "adj", definition: "expressing feelings in an unrestrained way", tier: 3, sense: "expressive" },
  { word: "enervate", pos: "verb", definition: "to drain of energy or vitality", tier: 3, sense: "weaken" },
  { word: "ennui", pos: "noun", definition: "weary boredom from lack of excitement", tier: 3, sense: "boredom" },
  { word: "equanimity", pos: "noun", definition: "calmness of mind under stress", tier: 3, sense: "calm" },
  { word: "esoteric", pos: "adj", definition: "understood by only a small, specialized group", tier: 3, sense: "specialized" },
  { word: "eschew", pos: "verb", definition: "to deliberately avoid or abstain from", tier: 3, sense: "avoid" },
  { word: "exculpate", pos: "verb", definition: "to show that someone is not guilty", tier: 3, sense: "defend" },
  { word: "expedient", pos: "adj", definition: "convenient and practical though possibly improper", tier: 3, sense: "practical" },
  { word: "extant", pos: "adj", definition: "still in existence; surviving", tier: 3, sense: "surviving" },
  { word: "fatuous", pos: "adj", definition: "silly and pointlessly self-satisfied", tier: 3, sense: "foolish" },
  { word: "fervor", pos: "noun", definition: "intense and passionate feeling", tier: 3, sense: "forceful" },
  { word: "flout", pos: "verb", definition: "to openly disregard a rule", tier: 3, sense: "defy" },
  { word: "germane", pos: "adj", definition: "relevant to the matter at hand", tier: 3, sense: "relevant" },
  { word: "grandiloquent", pos: "adj", definition: "using lofty language to impress", tier: 3, sense: "pompous" },
  { word: "harangue", pos: "noun", definition: "a lengthy, aggressive lecture", tier: 3, sense: "harsh-tone" },
  { word: "iconoclast", pos: "noun", definition: "a person who attacks cherished beliefs", tier: 3, sense: "rebel" },
  { word: "impecunious", pos: "adj", definition: "having little or no money", tier: 3, sense: "poor" },
  { word: "imperturbable", pos: "adj", definition: "unable to be upset or excited", tier: 3, sense: "calm" },
  { word: "impervious", pos: "adj", definition: "unable to be affected or penetrated", tier: 3, sense: "resistant" },
  { word: "inchoate", pos: "adj", definition: "just begun and not yet fully formed", tier: 3, sense: "undeveloped" },
  { word: "incontrovertible", pos: "adj", definition: "impossible to deny or dispute", tier: 3, sense: "certain" },
  { word: "indolent", pos: "adj", definition: "habitually avoiding effort", tier: 3, sense: "lazy" },
  { word: "ineffable", pos: "adj", definition: "too great to be expressed in words", tier: 3, sense: "indescribable" },
  { word: "ingenuous", pos: "adj", definition: "innocent and unsuspecting", tier: 3, sense: "gullible" },
  { word: "inimical", pos: "adj", definition: "tending to obstruct or harm", tier: 3, sense: "hostility" },
  { word: "insidious", pos: "adj", definition: "proceeding harmfully in a subtle, hidden way", tier: 3, sense: "sneaky" },
  { word: "intractable", pos: "adj", definition: "hard to control or solve", tier: 3, sense: "inflexible" },
  { word: "inveterate", pos: "adj", definition: "having a long-established habit unlikely to change", tier: 3, sense: "habitual" },
  { word: "irascible", pos: "adj", definition: "easily provoked to anger", tier: 3, sense: "angry" },
  { word: "itinerant", pos: "adj", definition: "traveling from place to place for work", tier: 3, sense: "wandering" },
  { word: "loquacious", pos: "adj", definition: "very talkative", tier: 3, sense: "wordy" },
  { word: "magnanimous", pos: "adj", definition: "generous and forgiving, especially toward a rival", tier: 3, sense: "kind" },
  { word: "malleable", pos: "adj", definition: "easily influenced or shaped", tier: 3, sense: "flexible" },
  { word: "maverick", pos: "noun", definition: "an independent-minded person who resists the group", tier: 3, sense: "rebel" },
  { word: "mercurial", pos: "adj", definition: "subject to sudden unpredictable mood changes", tier: 3, sense: "fickle" },
  { word: "myriad", pos: "adj", definition: "countless or extremely numerous", tier: 3, sense: "abundant" },
  { word: "nascent", pos: "adj", definition: "just coming into existence and beginning to develop", tier: 3, sense: "undeveloped" },
  { word: "obdurate", pos: "adj", definition: "stubbornly refusing to change one's mind", tier: 3, sense: "inflexible" },
  { word: "obfuscate", pos: "verb", definition: "to make something deliberately unclear", tier: 3, sense: "conceal" },
  { word: "obsequious", pos: "adj", definition: "excessively eager to please or obey", tier: 3, sense: "servile" },
  { word: "officious", pos: "adj", definition: "offering unwanted help or advice", tier: 3, sense: "meddling" },
  { word: "opaque", pos: "adj", definition: "impossible to see through or understand", tier: 3, sense: "unclear" },
  { word: "opulent", pos: "adj", definition: "displaying great wealth", tier: 3, sense: "flashy" },
  { word: "ostracize", pos: "verb", definition: "to exclude someone from a group", tier: 3, sense: "exclude" },
  { word: "panacea", pos: "noun", definition: "a supposed cure for all problems", tier: 3 },
  { word: "paucity", pos: "noun", definition: "the presence of something in too small an amount", tier: 3, sense: "insufficient" },
  { word: "pedantic", pos: "adj", definition: "overly concerned with minor rules and details", tier: 3, sense: "meddling" },
  { word: "penchant", pos: "noun", definition: "a strong habitual liking for something", tier: 3 },
  { word: "perfunctory", pos: "adj", definition: "done as a routine duty, without real care", tier: 3, sense: "hasty" },
  { word: "pernicious", pos: "adj", definition: "having a gradual and deadly harmful effect", tier: 3, sense: "sneaky" },
  { word: "petulant", pos: "adj", definition: "childishly sulky and bad-tempered", tier: 3, sense: "irritable" },
  { word: "phlegmatic", pos: "adj", definition: "unemotional and stolidly calm", tier: 3, sense: "calm" },
  { word: "platitude", pos: "noun", definition: "a dull remark offered as though it were profound", tier: 3, sense: "unoriginal" },
  { word: "polemic", pos: "noun", definition: "a strong verbal or written attack on an opinion", tier: 3, sense: "harsh-tone" },
  { word: "ponderous", pos: "adj", definition: "slow and heavy; dull and labored", tier: 3, sense: "slow" },
  { word: "presage", pos: "verb", definition: "to be a sign or warning of something to come", tier: 3, sense: "foretell" },
  { word: "prevaricate", pos: "verb", definition: "to speak evasively to avoid the truth", tier: 3, sense: "deception" },
  { word: "probity", pos: "noun", definition: "complete honesty and moral uprightness", tier: 3, sense: "integrity" },
  { word: "proclivity", pos: "noun", definition: "a natural tendency, often toward something bad", tier: 3 },
  { word: "profligate", pos: "adj", definition: "recklessly wasteful with money or resources", tier: 3, sense: "wasteful" },
  { word: "propensity", pos: "noun", definition: "an inclination to behave a certain way", tier: 3 },
  { word: "quiescent", pos: "adj", definition: "in a state of inactivity or dormancy", tier: 3, sense: "unchanging" },
  { word: "quixotic", pos: "adj", definition: "idealistic to an impractical degree", tier: 3, sense: "idealistic" },
  { word: "recalcitrant", pos: "adj", definition: "stubbornly resistant to authority", tier: 3, sense: "defy" },
  { word: "recondite", pos: "adj", definition: "dealing with a subject too deep for most people", tier: 3, sense: "specialized" },
  { word: "redolent", pos: "adj", definition: "strongly suggestive or fragrant of something", tier: 3, sense: "evocative" },
  { word: "reprove", pos: "verb", definition: "to express disapproval of someone's conduct", tier: 3, sense: "criticize" },
  { word: "sagacious", pos: "adj", definition: "showing keen judgment and deep wisdom", tier: 3, sense: "shrewd" },
  { word: "salient", pos: "adj", definition: "most noticeable or important", tier: 3, sense: "noticeable" },
  { word: "sanguine", pos: "adj", definition: "cheerfully optimistic in a difficult situation", tier: 3, sense: "optimistic" },
  { word: "sardonic", pos: "adj", definition: "grimly mocking or scornful", tier: 3, sense: "mocking" },
  { word: "soporific", pos: "adj", definition: "tending to induce sleep", tier: 3, sense: "dull" },
  { word: "specious", pos: "adj", definition: "seeming right but actually wrong", tier: 3, sense: "fake" },
  { word: "sporadic", pos: "adj", definition: "occurring at irregular intervals", tier: 3, sense: "occasional" },
  { word: "strident", pos: "adj", definition: "loud and harsh in tone", tier: 3, sense: "noise" },
  { word: "supercilious", pos: "adj", definition: "behaving as though superior to others", tier: 3, sense: "arrogant" },
  { word: "surreptitious", pos: "adj", definition: "done secretly to avoid being noticed", tier: 3, sense: "secret" },
  { word: "sycophant", pos: "noun", definition: "a person who flatters to gain advantage", tier: 3, sense: "servile" },
  { word: "taciturn", pos: "adj", definition: "saying very little by nature", tier: 3, sense: "reserved" },
  { word: "tirade", pos: "noun", definition: "a long angry speech of criticism", tier: 3, sense: "harsh-tone" },
  { word: "torpor", pos: "noun", definition: "a state of physical or mental inactivity", tier: 3, sense: "tired" },
  { word: "truculent", pos: "adj", definition: "eager to argue or fight", tier: 3, sense: "hostility" },
  { word: "vacillate", pos: "verb", definition: "to waver between different opinions", tier: 3, sense: "undecided" },
  { word: "venerate", pos: "verb", definition: "to regard with deep respect", tier: 3, sense: "respect" },
  { word: "veracity", pos: "noun", definition: "conformity to the truth; accuracy", tier: 3, sense: "integrity" },
  { word: "vicarious", pos: "adj", definition: "experienced through another person rather than firsthand", tier: 3 },
  { word: "vitriolic", pos: "adj", definition: "filled with bitter criticism", tier: 3, sense: "harsh-tone" },
  { word: "wanton", pos: "adj", definition: "deliberately cruel or destructive without cause", tier: 3, sense: "cruel" },
  { word: "zenith", pos: "noun", definition: "the highest point reached", tier: 3, sense: "peak" },
];

/** Fast lookup by headword. Words are unique across the list. */
export const VOCAB_BY_WORD: Map<string, VocabWord> = new Map(
  VOCAB_WORDS.map((w) => [w.word, w])
);

export function getVocabWord(word: string): VocabWord | undefined {
  return VOCAB_BY_WORD.get(word.toLowerCase());
}

export const VOCAB_TOTAL = VOCAB_WORDS.length;
